apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - x.x.x.x-x.x.x.x  # Cambia con il tuo range IP

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: ubuntumaster  # (master e worker)
  - matchLabels:
      kubernetes.io/hostname: ubuntuworker
